// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_blog_demo::comment_removed {

    use aptos_blog_demo::article::{Self, CommentRemoved};

    public fun article_id(comment_removed: &CommentRemoved): u128 {
        article::comment_removed_article_id(comment_removed)
    }

    public fun comment_seq_id(comment_removed: &CommentRemoved): u64 {
        article::comment_removed_comment_seq_id(comment_removed)
    }

}
