// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_test_proj1::aptos_test_proj1_init {
    use aptos_test_proj1::day_summary;
    use aptos_test_proj1::genesis_account;
    use aptos_test_proj1::order;
    use aptos_test_proj1::product;

    public entry fun initialize(account: &signer) {
        genesis_account::initialize(account);
        order::initialize(account);
        product::initialize(account);
        day_summary::initialize(account);
    }

}
