// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_blog_demo::article_aggregate {
    use aptos_blog_demo::article;
    use aptos_blog_demo::article_add_comment_logic;
    use aptos_blog_demo::article_create_logic;
    use aptos_blog_demo::article_delete_logic;
    use aptos_blog_demo::article_remove_comment_logic;
    use aptos_blog_demo::article_update_comment_logic;
    use aptos_blog_demo::article_update_logic;
    use std::string::String;

    public entry fun create(
        account: &signer,
        title: String,
        body: String,
        owner: address,
    ) {
        let article_created = article_create_logic::verify(
            account,
            title,
            body,
            owner,
        );
        let article = article_create_logic::mutate(
            account,
            &article_created,
        );
        article::add_article(article);
        article::emit_article_created(article_created);
    }

    public entry fun update(
        account: &signer,
        article_id: u128,
        title: String,
        body: String,
        owner: address,
    ) {
        let article = article::remove_article(article_id);
        let article_updated = article_update_logic::verify(
            account,
            title,
            body,
            owner,
            &article,
        );
        let updated_article = article_update_logic::mutate(
            account,
            &article_updated,
            article,
        );
        article::update_version_and_add(updated_article);
        article::emit_article_updated(article_updated);
    }

    public entry fun delete(
        account: &signer,
        article_id: u128,
    ) {
        let article = article::remove_article(article_id);
        let article_deleted = article_delete_logic::verify(
            account,
            &article,
        );
        let updated_article = article_delete_logic::mutate(
            account,
            &article_deleted,
            article,
        );
        article::drop_article(updated_article);
        article::emit_article_deleted(article_deleted);
    }

    public entry fun add_comment(
        account: &signer,
        article_id: u128,
        commenter: String,
        body: String,
        owner: address,
    ) {
        let article = article::remove_article(article_id);
        let comment_added = article_add_comment_logic::verify(
            account,
            commenter,
            body,
            owner,
            &article,
        );
        let updated_article = article_add_comment_logic::mutate(
            account,
            &comment_added,
            article,
        );
        article::update_version_and_add(updated_article);
        article::emit_comment_added(comment_added);
    }

    public entry fun remove_comment(
        account: &signer,
        article_id: u128,
        comment_seq_id: u64,
    ) {
        let article = article::remove_article(article_id);
        let comment_removed = article_remove_comment_logic::verify(
            account,
            comment_seq_id,
            &article,
        );
        let updated_article = article_remove_comment_logic::mutate(
            account,
            &comment_removed,
            article,
        );
        article::update_version_and_add(updated_article);
        article::emit_comment_removed(comment_removed);
    }

    public entry fun update_comment(
        account: &signer,
        article_id: u128,
        comment_seq_id: u64,
        commenter: String,
        body: String,
        owner: address,
    ) {
        let article = article::remove_article(article_id);
        let comment_updated = article_update_comment_logic::verify(
            account,
            comment_seq_id,
            commenter,
            body,
            owner,
            &article,
        );
        let updated_article = article_update_comment_logic::mutate(
            account,
            &comment_updated,
            article,
        );
        article::update_version_and_add(updated_article);
        article::emit_comment_updated(comment_updated);
    }

}
