// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_blog_demo::comment_updated {

    use aptos_blog_demo::article::{Self, CommentUpdated};
    use std::string::String;

    public fun article_id(comment_updated: &CommentUpdated): u128 {
        article::comment_updated_article_id(comment_updated)
    }

    public fun comment_seq_id(comment_updated: &CommentUpdated): u64 {
        article::comment_updated_comment_seq_id(comment_updated)
    }

    public fun commenter(comment_updated: &CommentUpdated): String {
        article::comment_updated_commenter(comment_updated)
    }

    public fun body(comment_updated: &CommentUpdated): String {
        article::comment_updated_body(comment_updated)
    }

    public fun owner(comment_updated: &CommentUpdated): address {
        article::comment_updated_owner(comment_updated)
    }

}
